// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrionPOS.Infra.Persistence;

#nullable disable

namespace OrionPOS.Infra.Migrations
{
    [DbContext(typeof(OrionPosDbContext))]
    partial class OrionPosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrionPOS.Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Cardapio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid?>("TabelaPrecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tabela_preco_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TabelaPrecoId");

                    b.HasIndex("TenantId");

                    b.ToTable("cardapios", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.CardapioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("CardapioId")
                        .HasColumnType("uuid")
                        .HasColumnName("cardapio_id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("CardapioId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("cardapio_itens", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("MaxSelecoes")
                        .HasColumnType("integer")
                        .HasColumnName("max_selecoes");

                    b.Property<int>("MinSelecoes")
                        .HasColumnType("integer")
                        .HasColumnName("min_selecoes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("modifier_groups", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ModifierOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_group_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("PrecoAdicional")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("preco_adicional");

                    b.HasKey("Id");

                    b.HasIndex("ModifierGroupId");

                    b.ToTable("modifier_options", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.PrecoVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<decimal>("Preco")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("preco");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("preco_promocional");

                    b.Property<Guid>("ProdutoVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_variant_id");

                    b.Property<Guid>("TabelaPrecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tabela_preco_id");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoVariantId");

                    b.HasIndex("TabelaPrecoId", "ProdutoVariantId")
                        .IsUnique();

                    b.ToTable("precos_variants", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<bool>("ControlaEstoque")
                        .HasColumnType("boolean")
                        .HasColumnName("controla_estoque");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_preparo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TenantId");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ProdutoModifierGroup", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_group_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("ProdutoId", "ModifierGroupId");

                    b.HasIndex("ModifierGroupId");

                    b.ToTable("produto_modifier_groups", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ProdutoVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("produto_variants", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.TabelaPreco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("tabelas_preco", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Cardapio", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.TabelaPreco", "TabelaPreco")
                        .WithMany()
                        .HasForeignKey("TabelaPrecoId");

                    b.HasOne("OrionPOS.Domain.Catalogo.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaPreco");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.CardapioItem", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Cardapio", "Cardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrionPOS.Domain.Catalogo.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("OrionPOS.Domain.Catalogo.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Categoria", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ModifierGroup", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ModifierOption", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.ModifierGroup", "ModifierGroup")
                        .WithMany("Opcoes")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifierGroup");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.PrecoVariant", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.ProdutoVariant", "ProdutoVariant")
                        .WithMany("Precos")
                        .HasForeignKey("ProdutoVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrionPOS.Domain.Catalogo.TabelaPreco", "TabelaPreco")
                        .WithMany("Precos")
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoVariant");

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Produto", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("OrionPOS.Domain.Catalogo.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ProdutoModifierGroup", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.ModifierGroup", "ModifierGroup")
                        .WithMany("Produtos")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrionPOS.Domain.Catalogo.Produto", "Produto")
                        .WithMany("ModifierGroups")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifierGroup");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ProdutoVariant", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Produto", "Produto")
                        .WithMany("Variants")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.TabelaPreco", b =>
                {
                    b.HasOne("OrionPOS.Domain.Catalogo.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Cardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ModifierGroup", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.Produto", b =>
                {
                    b.Navigation("ModifierGroups");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.ProdutoVariant", b =>
                {
                    b.Navigation("Precos");
                });

            modelBuilder.Entity("OrionPOS.Domain.Catalogo.TabelaPreco", b =>
                {
                    b.Navigation("Precos");
                });
#pragma warning restore 612, 618
        }
    }
}
